# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EasyChair' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyChair
  pod 'Firebase/Core', '~> 4.13.0'
  pod 'Firebase/Auth'

  target 'EasyChairTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyChair-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EasyChair-tvOS

  target 'EasyChair-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
